### PR TITLE
Add support for VMware Workstation

### PR DESCRIPTION
**Pull request by zoontek**

### CODE REVIEW

**Comment by taylorotwell** [comment]
@joshfng thoughts on this?

**Comment by joshfng** [comment]
This should work, and the vmware_fusion box should work just fine with it also. LGTM

**Comment by joshfng** [comment]
Give me a few and I can test it on a windows box.

**Comment by joshfng** [comment]
Workstation requires a different plugin/license than fusion. @zoontek any chance you could let me debug using your license for workstation? joshfng@gmail.com if so.

**Comment by zoontek** [comment]
I made this quick PR at work, and now as I try at home, just figure out that the guest parameter is not for the provider configuration.

```
The following settings shouldn't exist: guest
```

**Comment by joshfng** [comment]
Feel free to commit a fix :)

**Comment by zoontek** [comment]
Done! Everything should work fine now :)

**Comment by joshfng** [comment]
Awesome. I don't really have a way to test this, and I'm not dropping another $80 for a workstation vagrant plugin. I use fusion :)

**Comment by zoontek** [comment]
I use Fusion too, because Workstation isn't available on OSX.
But the Vagrant doc refers at the same configuration: https://docs.vagrantup.com/v2/vmware/configuration.html

**Comment by joshfng** [comment]
It *should* work. I'd just really like to test it first.

**Comment by taylorotwell** [comment]
Wait, so you don't even actually use workstation? Then why are we adding this? :)

**Comment by zoontek** [comment]
For the people who will :)
As Vagrant use the same configuration for Fusion and Workstation, maybe people will expect support for both.

**Comment by taylorotwell** [comment]
Ah. Well we'll let someone who has workstation do this when the time comes since we can't test it.

**Comment by vmadev** [comment]
This works correctly. In fact, now cpu and memory is carried over to the vm whereas without it it was not.

Please note that windows users should 
remove Winnfsd if installed.

$vagrant plugin uninstall vagrant-winnfsd 

With Winnfsd installed performing a homestead halt will subsequently break the nfs connection and will require a reboot of the OS in order to reconnect. Removing it resolves the issue altogether.

**Comment by zoontek** [comment]
Actually, I'm always thinking this could be a better way to do it (because you can set the OS type:
@vmadev & @joshfng, could you test this in Fusion / Workstation please?

```ruby
["vmware_fusion", "vmware_workstation"].each do |vmware|
  config.vm.provider vmware do |v|
    v.vmx["displayName"] = settings["name"]
    v.vmx["memsize"] = settings["memory"]
    v.vmx["numvcpus"] = settings["cpus"]
    v.vmx["guestOS"] = "ubuntu-64"
  end
end
```

**Comment by joshfng** [comment]
@vmadev @zoontek the current memory and cpu settings block for fusion does indeed carry over to the vm:

```
vagrant@homestead:~$ free -m
             total       used       free     shared    buffers     cached
Mem:          3952        780       3172         17         22        179
-/+ buffers/cache:        577       3374
Swap:          767          0        767```

I'll try the combined block. If it works, I don't see why we couldn't merge this in. @vmadev you have workstation w/ vagrant plugin and can assist in testing?

**Comment by joshfng** [comment]
Confirmed that

```
["vmware_fusion", "vmware_workstation"].each do |vmware|
      config.vm.provider vmware do |v|
        v.vmx["displayName"] = "homestead"
        v.vmx["memsize"] = settings["memory"] ||= 2048
        v.vmx["numvcpus"] = settings["cpus"] ||= 1
        v.vmx["guestOS"] = "ubuntu-64"
      end
    end
```
functions as expected (for fusion at least). @zoontek could you please add that block to your PR and remove the standalone fusion block?

**Comment by zoontek** [comment]
As this PR is closed I have to create another one, so I prefer waiting for the @vmadev confirmation.

**Comment by vmadev** [comment]
The combined block also works for VMware Workstation on Windows.

**Comment by zoontek** [comment]
Thanks guys :+1:
If @taylorotwell is OK with that, I can create a new PR to add Workstation support, so.

**Comment by joshfng** [comment]
@zoontek I believe you can still update your repo and branch, and those changes will be reflected in this pr regardless of being closed or not.

**Comment by zoontek** [comment]
@joshfng After the PR closing, I delete the fork repo because it was located on my organisation account (I already have a fork of homestead on my personnal account) :/

**Comment by joshfng** [comment]
Ah gotcha. Well then go ahead and create a new PR. Be sure to mention it here so all involved can move to the new one. I'm sure @taylorotwell will consider it now that it's been fully tested :+1:

**Comment by zoontek** [comment]
I ask the Github team to convert my fork to a "standard" repo, so I don't have to use my organisation account.
The new PR is here: https://github.com/laravel/homestead/pull/174

**Pull request closed without merging**
