### PR TITLE
Add nginx config for Elgg sites

### LINKED ISSUE #615: Additional NGINX config for `elgg` sites
I am not sure if you accept additional configs, but I would be happy to make a PR:
https://gist.github.com/hypeJunction/846a3ebab798df83f35897e3e6b8eb26

### PR DESCRIPTION
**Pull request by hypeJunction**
Adds template shell config to easily bootstrap Elgg sites on Homestead.

Fixes #615

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks for the PR!

**Comment by hypeJunction** [comment]
My pleasure. Makes my life a lot easier as well :)

**Comment by svpernova09** [comment]
I'll tag a new release in a few days, I want to test out a mariadb issue so if you want to use this now just checkout the master branch.

**Comment by hypeJunction** [comment]
No stress. Thanks

**Pull request merged**
