### PR TITLE
Updated src/stubs/aliases to include vendor_bin

### PR DESCRIPTION
**Pull request by gxela**
added vendor_bin alias, so to add vendor/bin to path when run from root of project

### CODE REVIEW

**Comment by svpernova09** [comment]
I think I see what you're trying to do, but you're not using this anywhere. I would include a backwards compatible use case so the end user could see the intended use.

**Comment by matteoantoci** [comment]
Nice!

**Comment by gxela** [comment]
yes, I do use it. once I am inside the homestead machine in the project directory I type vendor_bin and it adds all those great tools into my PATH

**Comment by gxela** [comment]
Is this going to get merged? Over the years I have commited a few changes to Laravel, and you guys don't merge them. If you don't merge this, then you suck and so does Laravel.

**Pull request closed without merging**
