### PR TITLE
Vagrant >= 1.8.4 is not required anymore

### PR DESCRIPTION
**Pull request by taliptako**
We dont need to force people to use Vagrant >= 1.8.4

### CODE REVIEW

**Comment by morloderex** [comment]
I believe that the issues with vagrant versions piror to vagrant 1.8.4 will still have issues when running homestead.

**Comment by taliptako** [comment]
Many offical repositories of Linux distributions have older version from 1.8.4 so i also have and i'm manually removing this line always ...

**Comment by jonnywilliamson** [comment]
One of the biggest issues was this:
https://github.com/mitchellh/vagrant/pull/6493

Basically, trying to run gulp and npm in the homestead VM, (whilst running on windows host), caused a lot of issues because the filepaths created during NPM installation where too long.

It causes lots of errors, but finally the guys at Vagrant found a fix to that solution.

It might have arrived in vagrant 1.8.2 or similar, but there was a further bug that was squashed by version 1.8.4.

It now works reliably and as such, I think requiring a minimum of vagrant 1.8.4 is a good idea,

**Comment by Utkarsh-vishnoi** [comment]
Yeah i had the same problem too, but when i installed gulp on both in homestead and my host OS(windows). It worked.

**Pull request closed without merging**
