### PR TITLE
Update SSL support

### PR DESCRIPTION
**Pull request by KennedyTedesco**
There is no need of two nginx `server{}` for this purpose.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by taylorotwell** [comment]
You've tested this I assume?

**Comment by KennedyTedesco** [comment]
Sure! :)

**Comment by KennedyTedesco** [comment]
Side note: http://nginx.org/en/docs/http/configuring_https_servers.html#single_http_https_server

**Comment by taylorotwell** [comment]
Do we generate SSL certificates for non-SSL sites?

**Comment by KennedyTedesco** [comment]
Yes, we do. By default. It's a good thing, I guess.

**Pull request merged**
