### PR TITLE
Fix name/names bug

### PR DESCRIPTION
**Pull request by staudenmeir**
d2ffd7d only fixed the first of four occurrences.

### CODE REVIEW

**Comment by arielayaviri** [comment]
Hi everyone, thanks for the awesome tool. 
I tested in Virtual Box and setting the 'name' in Homestead.yaml still don't work to create a vm with a custom name. I had to set both 'name' and 'names'.

**Comment by staudenmeir** [comment]
@arielayaviri This PR hasn't been released yet.

**Comment by svpernova09** [comment]
Will tag shortly

**Comment by svpernova09** [comment]
Tagged https://github.com/laravel/homestead/releases/tag/v7.14.2

**Pull request merged**
