### PR TITLE
Add tests for shell script

### PR DESCRIPTION
**Pull request by DojoGeekRA**
@svpernova09 as discussed in #520, this PR add tests for the `init.sh` shell script.

It also makes a little refactor to improve code readability.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Shouldn't have a trait just called "Slug".. it should be something like `GeneratesSlugs`, etc.

**Comment by svpernova09** [comment]
`GenerateSlug`  would be a good name for it.


Thanks @DojoGeekRA I'll have a look at this later this afternoon.

**Comment by DojoGeekRA** [comment]
@taylorotwell you're right, that name makes more sense. It's fixed now.

And thanks @svpernova09 , let me know if you need anything else.

**Comment by svpernova09** [comment]
Thanks for the PR!

**Pull request merged**
