### PR TITLE
Preserve the right settings from an example settings file

### LINKED ISSUE #507: `homestead make` not respecting all Homestead.yaml.example settings
## Versions
  - Vagrant: 1.9.0
  - Provider: Virtualbox,
  - Homestead: 5.0.1

## Host operating system
MacOs 10.11.4

## Homestead.yaml.example
```yaml
ip: "192.168.10.10"
memory: "3072"
cpus: "1"
hostname: seotasks.app
name: seotasks.app
provider: virtualbox
version: 2.0.0
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - map: ~/Code
      to: /home/vagrant/Code/seo-tasks-backend
sites:
    - map: seotasks.app,
      to: /home/vagrant/Code/seo-tasks-backend/public
      schedule: true
databases:
    - reporting
    - testing_reporting
```

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: '3072'
cpus: '1'
hostname: seo-tasks-backend
name: seo-tasks-backend
provider: virtualbox
version: 2.0.0
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - { map: /Users/mcallan/Projects/seo-tasks-backend, to: /home/vagrant/Code/seo-tasks-backend }
sites:
    - { map: seo-tasks-backend.app, to: /home/vagrant/Code/seo-tasks-backend/public }
databases:
    - reporting
    - testing_reporting
```

## Vagrant up output
Not a Vagrant issue.

## Expected behavior

Running `vendor/bin/homestead make` will copy a `Homestead.yaml.example` file to `Homestead.yaml`, and then update the folders.map value from `~\Code` in the example file to the current path on the host OS. All other values from the example file will remain as is.

## Actual behavior

Since upgrading to Homestead 5, running `vendor/bin/homestead` still copies the `Homestead.yaml.example` file to `Homestead.yaml`, however it is ignoring the "schedule: true" value set in Homestead.yaml.example` under sites.

In addition, it is regenerating `hostname` and `name` values and not using the values set in `Homestead.yaml.example`.

## Steps to reproduce
1. `vendor/bin/homestead make`

### PR DESCRIPTION
**Pull request by DojoGeekRA**
Preserves the `name`, `hostname`, `site's schedule` and `site's type` settings when it is created from a `homestead.yaml|json.example` file.

It fixes #507

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans on adding all of this.

**Comment by taylorotwell** [comment]
Apparently we need this.

**Comment by taylorotwell** [comment]
Is this ready or not?

**Comment by svpernova09** [comment]
@DojoGeekRA Thanks for the PR, ping me when you're ready for this to be merged.

**Comment by DojoGeekRA** [comment]
It is ready @svpernova09

**Comment by svpernova09** [comment]
Thanks!

**Pull request merged**
