### PR TITLE
Migrate and seed aliases

### PR DESCRIPTION
**Pull request by martinbean**
Add helpful `migrate` and `seed` aliases.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I agree that this is helpful but just don't want to open the door to a lot more alias PRs. :smile:

**Comment by svpernova09** [comment]
@martinbean 

fwiw, if you're using homestead per project you can easily add all the aliases you want by using the aliases flag via the make command.

**Comment by martinbean** [comment]
@taylorotwell Fair enough. Understandable! :smile: 

@svpernova09 Already aware, thanks. I just find myself adding the same aliases for each project, so thought I’d try and get them merged.

**Comment by jonnywilliamson** [comment]
@svpernova09 Could you explain that a little more please? I don't quiet follow what you mean.

Thank you.

**Comment by svpernova09** [comment]
@jonnywilliamson 

Have a look at the docs about [per project install](http://laravel.com/docs/5.1/homestead#per-project-installation) When you run `php vendor/bin/homestead` add `--aliases` and it will create an aliases file in the folder you can add all the aliases you want there.

**Comment by jonnywilliamson** [comment]
@svpernova09 Ah ok!

I haven't had to do per project installs, so I hadn't noticed that option. Thank you.

**Pull request closed without merging**
