### PR TITLE
Add wildcard & use_wildcard SSL Site options

### PR DESCRIPTION
**Pull request by svpernova09**
## TODO:

- [x] Apache Support
- [x] nginx Support

## Documenation:
Create an use wildcard for a site:
```
    - map: foo.domain.test
      to: /home/vagrant/domain
      wildcard: "yes"
      use_wildcard: "yes"
```

Create but do *not* use wildcard for a site:
```
    - map: foo.domain.test
      to: /home/vagrant/domain
      wildcard: "yes"
      use_wildcard: "no"
```

### CODE REVIEW

**Comment by svpernova09** [comment]
Currently does *not* support Apache

**Comment by browner12** [comment]
What's the scenario when you would want to create the wildcard cert, but not use it?

**Comment by svpernova09** [comment]
> What's the scenario when you would want to create the wildcard cert, but not use it?
The scenario that would 100% happen if I hadn't built that already :D

**Comment by browner12** [comment]
hah, fair enough.

would it make more sense to default it to use the cert, and only make people add another setting if they want to override it off?

**Comment by svpernova09** [comment]
> would it make more sense to default it to use the cert, and only make people add another setting if they want to override it off?

I didn't default to the wildcard because I'm not sure how many users really want wildcards. I've run into needing them a few time myself and it's a bit of a hack. Felt better to formalize the support and allow users to opt in.

**Comment by deviantintegral** [comment]
Have you seen https://github.com/FiloSottile/mkcert ? We're using it on a project now and it is working well.

**Comment by svpernova09** [comment]
I believe this is ready to go. Added Apache support, also squashed the bug where we were not properly disabling the nginx service when installing Apache.

Also refactored to `scripts/restart-webserver.sh` to dynamically figure out *which* web sever we should start.

I'm going to leave this in master for a few days and tag a release likely next week.

**Pull request merged**
