### PR TITLE
Fix for apache log dir variable and log file per site

### PR DESCRIPTION
**Pull request by padalec**
Before my changes all logs was placed in root folder and all sites was saved to one file for access log and one for error log.

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks for the PR.

Is the leading `\` before `${APACHE_LOG_DIR}` required? If not lets remove.

**Comment by padalec** [comment]
Yes its, because without \ when this setting was saved to apache config file this variable does not exists is replaced by empty string

**Comment by svpernova09** [comment]
Thanks!

**Comment by padalec** [comment]
You welcome :)

**Pull request merged**
