### PR TITLE
Issue template: pls update!!

### PR DESCRIPTION
**Pull request by andrewhood125**
Preview here: https://github.com/andrewhood125/homestead/blob/update-issue-template/.github/ISSUE_TEMPLATE.md

### CODE REVIEW

**Comment by svpernova09** [comment]
Add a mention that Virtualbox 5.1 is the current version. Seeing LOTS of people who have 5.0 and do the About -> Check for Updates and it reports there are none, yet they're still having vagrant issues cause they're on the 5.0

tl;dr You have to download 5.1 to update 5.0 -> 5.1

**Comment by andrewhood125** [comment]
Yep, I'm with you. One sec.

**Comment by svpernova09** [comment]
Squash commits and we're good

**Comment by andrewhood125** [comment]
I also `###` -> `##` You get the `hr` which I think helps keep it organized. Squashed. (You can also squash and merge from GitHub interface).

**Comment by svpernova09** [comment]
`You can also squash and merge from GitHub interface` TIL

**Pull request merged**
