### PR TITLE
Generate SSL-DEV

### PR DESCRIPTION
**Pull request by juliolustosa**
A suggestion to create sites automatically with ssl for testing.
Congratulations on the excellent work, I am a big fan of Laravel

### CODE REVIEW

**Comment by mmeyer2k** [comment]
I submitted a similar PR (#112) recently which was closed.

**Comment by svpernova09** [comment]
I think this PR is a bit cleaner than #112. I'd like to see the CSR variables be extracted so they could easily be set or fully generalized.

:+1: this is a decent option to enable SSL

**Comment by taylorotwell** [comment]
Yeah, don't like the hard-coded CSR stuff and all that. Also seems like you could just redirect to the 443 server instead of duplicating blocks.

**Comment by juliolustosa** [comment]
I understand , thank you

**Pull request closed without merging**
