### PR TITLE
Change logo to work on Dark Theme

### PR DESCRIPTION
**Pull request by xiCO2k**

### CODE REVIEW

**Comment by svpernova09** [comment]
@taylorotwell @driesvints Do we have official dark theme logos?

**Comment by xiCO2k** [comment]
@svpernova09 The problem is GitHub we don't have a way on the readme to know if the dark theme is active, and we can't rely on the media query since we can have people that have dark mode on the system but have light mode on github.

And that will show like this:

image

**Comment by xiCO2k** [comment]
@taylorotwell asked me to do the same on each laravel repo.

https://github.com/laravel/scout/pull/526#issuecomment-924044844

**Comment by svpernova09** [comment]
> @svpernova09 The problem is GitHub we don't have a way on the readme to know if the dark theme is active, and we can't rely on the media query since we can have people that have dark mode on the system but have light mode on github.
> 
> And that will show like this:
> 
> image

No worries at all! I just wanted to make sure someone upstream knew what was going on, thanks for doing this!

**Comment by xiCO2k** [comment]
Thanks

**Pull request merged**
