### PR TITLE
Script to allow Homestead to be globally accessible in Windows

### PR DESCRIPTION
**Pull request by axelitus**
Also the init will ask if you want to add Homestead to the PATH environment variable and take care of this for you.

### CODE REVIEW

**Comment by svpernova09** [comment]
Will have a look. Not sure if this is something we should delegate to Homestead, or ensure the user performs this themselves.

**Comment by andrewhood125** [comment]
`.bat` 🤢

**Comment by andrewhood125** [comment]
Maybe it's time we fork homestead into homestead-win..

**Comment by svpernova09** [comment]
No reason to fork. But I would like to move `init.bat` to `init.ps1` And clean up the code. <3 PowerShell

**Comment by svpernova09** [comment]
@axelitus Thanks for the PR. Going to hold off on this because I'd rather not have the Windows version acting differently than the Linux version (if at all possible). I'm also not sure this is something Homestead should be responsible for.

Thanks.

**Comment by axelitus** [comment]
Ok, I agree that it should work likewise in both platforms.

I think a win-specific version of the [Accessing Homestead Globally](https://laravel.com/docs/5.3/homestead#accessing-homestead-globally) doc page is missing though as it could be understood that in windows there is no way to access homestead globally, which is not the case.

**Comment by svpernova09** [comment]
@axelitus Feel free to write something up and submit a PR to docs.

**Comment by axelitus** [comment]
Will do ;)

**Pull request closed without merging**
