### PR TITLE
Added systemd script for services startup at boot (automatically)

### PR DESCRIPTION
**Pull request by litan1106**
Added systemd script for services startup at boot (automatically)

Otherwise, you have to start nginx, php-fpm, redis-server and mysql servers manually.

### CODE REVIEW

**Comment by svpernova09** [comment]
Yikes, 2 weeks. I'm *really* not ignoring this. I just want to do some more reading around WSL and their intentions around services and systemd. I'm wanting to make sure we don't paint Homestead into a corner in regards to having to make drastic changes.

**Comment by litan1106** [comment]
> Yikes, 2 weeks. I'm _really_ not ignoring this. I just want to do some more reading around WSL and their intentions around services and systemd. I'm wanting to make sure we don't paint Homestead into a corner in regards to having to make drastic changes.

@svpernova09  No worry. I have been learning the WSL stuff as well, but systemd and static ip is the hardest thing in WSL.

**Comment by svpernova09** [comment]
Thanks!

**Comment by Houbsi** [comment]
>  static ip is the hardest thing in WSL.

I Hosted all domains to 127.0.0.1 and it works like a charm. So no static IP needed.

**Comment by svpernova09** [comment]
> 
> 
> > static ip is the hardest thing in WSL.
> 
> I Hosted all domains to 127.0.0.1 and it works like a charm. So no static IP needed.

This is great but once you get to dealing with containers (Docker Desktop -> WSL) it gets a bit weird to grab proper IPs for containers, but I think that's more a "WSL magic doesn't quite work this far yet" issue.

**Pull request merged**
