### PR TITLE
Automatically set the users /etc/hosts or Windows hosts file with the 

### PR DESCRIPTION
**Pull request by alnutile**
help of https://github.com/cogitatio/vagrant-hostsupdater

I post here https://alfrednutile.info/posts/184 some very easy steps to using this library. Also I link to http://sherriflemings.blogspot.ca/2015/03/laravel-homestead-on-windows-8.html which shows it being used in Windows (and I used it there a bit).

Just thought if this was part of the Homestead install docs it might be a nice addition.

### CODE REVIEW

**Comment by taylorotwell** [comment]
It causes errors if the plugin isn't installed.

**Comment by Ingramz** [comment]
@alnutile some suggestions, because I'd like this to end up in homestead.

Surround your code with this, so that it's not required to have it installed
```rb
if Vagrant.has_plugin?("vagrant-hostsupdater")
  # plugin specific code here
end
```

and instead of duplicating aliases in config, capture them from `sites` -> `map` values ([usage](https://github.com/laravel/homestead/blob/master/scripts/homestead.rb#L155-L189)), unless there is a reason why one should define them separately.

**Comment by alnutile** [comment]
Odd thing seems this is already in Laravel Homestead just not documented?

https://github.com/laravel/homestead/blob/master/Vagrantfile#L34-L36

@taylorotwell would it be helpful for me to do a PR and update the docs?

**Comment by jonnywilliamson** [comment]
I think this was related to https://github.com/laravel/homestead/pull/159

**Comment by alnutile** [comment]
@jonnywilliamson thanks for the link

**Pull request closed without merging**
