### PR TITLE
Added SSL support

### PR DESCRIPTION
**Pull request by JamShady**
Added SSL support with automatically generated certificates per host during the build process

### CODE REVIEW

**Comment by taylorotwell** [comment]
So in usage it would look like `ssl: true` in your site declaration?

**Comment by taylorotwell** [comment]
When I test this I'm getting the following Nginx error:

```
400 Bad Request

The plain HTTP request was sent to HTTPS port
```

**Comment by taylorotwell** [comment]
Nevermind. Helps if you put HTTPS in your browser address bar. :smile: :heart:

**Comment by gpspake** [comment]
If I add `ssl: "true"` to Homestead.yaml like:
```
sites:
    - map: laravel.uni.edu
      to: "/home/vagrant/uni/public"
      ssl: "true"
```
and run `vagrant up`, the process completes but I can't get to the site in my browser (with or without https). Simply removing that line and re-running `vagrant up` works fine and I can get to my app. 

I should note that I had to add quotes to "true" because using `ssl: true`, like @taylorotwell mentioned above, returns the error `Shell provisioner 'args' must be a string or array.` on `vagrant up` - this might be part of my problem.

Is there something obvious I'm missing here?

**Comment by GrahamCampbell** [comment]
Please don't comment on closed pull requests with issues.

**Comment by gpspake** [comment]
@GrahamCampbell sorry. Issues seem to be disabled on this repo :/

**Pull request merged**
