### PR TITLE
Adding environment variables per sites for laravel apache and symfony…

### PR DESCRIPTION
**Pull request by WaReZzZz**
… same usage as global environment variables
for exemple

```
sites:
    - map: xxxxxx.com
      to: /home/vagrant/Code/xxxxxx/web
      variables:
          - key: PROJECT
            value: xxxxx
          - key: PATHDATA
            value: xxxxxxxxxx/xxxxxxxxx/xxxxx
```

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks for the PR. Sorry for the delay but I'll have a look at this later this evening (US time)

**Comment by it-can** [comment]
I am getting this error after this PR

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* Shell provisioner `args` must be a string or array
```

**Comment by svpernova09** [comment]
Thanks for the report.

Use git checkout to check out a release version.

Master may not always be in a workable state.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by it-can** [comment]
Ok, version 5.2.4 works correct, but this change only works when adding variables to every site in your Homestead.yaml file...

**Comment by WaReZzZz** [comment]
@it-can and @svpernova09  i'll correct it tonight (France time)

**Comment by svpernova09** [comment]
Thanks!

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by WaReZzZz** [comment]
Thanks to you
I've corrected it earlier this should be solved by the pull #565

**Pull request merged**
