### PR TITLE
Allow user to specify their own options for ngrok

### PR DESCRIPTION
**Pull request by vblinden**
Hi guys,

This allows the user to specify the region (-region=eu) or subdomain (-subdomain=test1234). This may come in handy for people from europe.

Thanks.

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks for the PR, will have a look at this later today.

**Comment by andrewhood125** [comment]
Can we add something in the usage for this feature?

**Comment by svpernova09** [comment]
Docs should be supplemented here https://laravel.com/docs/5.4/homestead#sharing-your-environment

**Comment by vblinden** [comment]
Sure, I could add a note in the usage. Should I include every ngrok command or just a note that you can add ngrok commands after the first command?

And also a section in the documentation?

**Comment by andrewhood125** [comment]
I had to look up `${@:2}`. I was thinking something along the lines of:

```
function share() {
    if [[ "$1" ]]
    then
        ngrok http ${@:2} -host-header="$1" 80
    else
        echo "Error: missing required parameters."
        echo "Usage: "
        echo "  share domain "
        echo "Invocation with extra params passed directly to ngrok" 
        echo "  share domain -region=eu -subdomain=test1234"
    fi
}
```

Is that how it would be used @vblinden?

**Comment by vblinden** [comment]
@andrewhood125 That is exactly how this would be used. Shall I add this to the pull request?

**Comment by andrewhood125** [comment]
That would be my 2 cents. Because it wasn't immediately obvious to me what the ${@:2} did but I'll defer to others.

**Pull request merged**
