### PR TITLE
Add the host file update + unit test

### PR DESCRIPTION
**Pull request by ezimuel**
This PR adds the update of the host file during the `make` command. It supports Linux/Mac and Windows.
Moreover, the PR adds the unit test to the project, including a first test on the `make` command.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't want Homestead to be touching the hosts file.

**Comment by ezimuel** [comment]
@taylorotwell why? You don't think people can benefit from this feature?

**Comment by ptondereau** [comment]
@ezimuel I think it's the responsability of end developer to add a helper to its project. Homestead's project should concern only required configuration to run. It's not mandatory to add hosts entries to run it.

**Comment by ezimuel** [comment]
@ptondereau actually is mandatory. The Homestead project works out of the box using the host name `homestead.app`. You must add it in your host file to use it (with default IP address `192.168.10.10`). This is also documented in the documentation [here](https://laravel.com/docs/5.4/homestead#configuring-homestead) as requirement. I only provided an automatic way to add the hostname in the host file, if not present.

That said, it's perfectly fine to reject this PR, but I would like to know why from @taylorotwell. I don't see technical cons about that.

**Comment by svpernova09** [comment]
@ezimuel Thanks for taking the time for the PR.

 IMHO It's not vagrant's responsibility to set host names, and since doing so would require sudo access on *nix like systems, Homestead doesn't want to assume the risk that comes along with that. We also would have to rely on sudo-esque admin privileges in Powershell to accomplish the same thing on Windows. It's just MUCH easier and LESS risk for Homestead to not be responsible for that.

There are Vagrant plugins out there that will manage this for you. We've had a number of attempts to merge this functionality into Homestead and it's something we've always adamantly avoided.

I'd love to see a PR with a test for make command in a separate PR though.

**Comment by taylorotwell** [comment]
I basically agree with @svpernova09. Every time we have tried to manage the hosts file within Homestead it has had to be reverted and I find it simpler to just use Gasmask or even edit the host file manually.

**Comment by ezimuel** [comment]
@taylorotwell and @svpernova09 thanks for you reply. Now, I can see your point but still I think that editing a text file is not a big risk. Maybe, the [vagrant-hostmanager](https://github.com/devopsgroup-io/vagrant-hostmanager) it's a better alternative.
Anyway, I will create a new PR to separate the unit test for the make command, included in this PR.

**Pull request closed without merging**
