### PR TITLE
Add timestamp directory to mysql backups.

### PR DESCRIPTION
**Pull request by ethanclevenger91**
Addresses #1392 

I read concerns about increased complexity but I'm not sure what qualifies as "complex"

### CODE REVIEW

**Comment by svpernova09** [comment]
Database Backup users should chime in, I don't use this feature so I wouldn't be affected.

**Comment by ethanclevenger91** [comment]
At this time, Homestead doesn't offer any utility for importing databases, just exporting, so it definitely comes down to per-user use.

**Comment by svpernova09** [comment]
Leaving open for a few more days, then will merge.

**Comment by svpernova09** [comment]
Thanks!

**Pull request merged**
