### PR TITLE
Hotfix - changed directories in init script from src/stub/ to resources/

### PR DESCRIPTION
**Pull request by Pancrisp**

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks for the PR!

**Comment by DojoGeekRA** [comment]
@svpernova09  I'm sorry for missing that ones, seems that we need tests for the shell scripts 😅

Thanks @Pancrisp!

**Comment by svpernova09** [comment]
@DojoGeekRA No worries at all. I intentionally haven't tagged another release until I can sit down and test these changes.

I've been rolling around the idea of some kind of test suite like that but I just dunno.

**Comment by DojoGeekRA** [comment]
@svpernova09 great to know, thanks for that!

And yup, neither do i know how to test those, buts seems like fun to figure it out.

**Comment by svpernova09** [comment]
I think we should try something like this: https://github.com/laravel/homestead/blob/master/tests/Settings/YamlSettingsTest.php#L18-L20

Create a test folder and run the actual commands and inspect file output. Might be worth looking into.

**Comment by DojoGeekRA** [comment]
@svpernova09 looks good, let's give it a shoot. I will tackle this tonight.

**Pull request merged**
