### PR TITLE
Automatically add hosts to hostsfile

### PR DESCRIPTION
**Pull request by ArjandeV**
Using vagrant plugin:
https://github.com/cogitatio/vagrant-hostsupdater

### CODE REVIEW

**Comment by mmeyer2k** [comment]
PR #91 did exactly the same thing but was recently closed.

**Comment by erikbelusic** [comment]
would love this as well!

vvv (wordpress dev vagrant) has this feature and it is awesome to never have to open up the hosts file. makes starting new projects so much quicker.

**Comment by svpernova09** [comment]
IMHO it's bad form to make Homestead depend on vagrant plugins. It also would be concerning to me that Homestead would be touching my hosts file. If I wanted this functionality I'd do it outside of Homestead.

**Comment by dmyers** [comment]
This is a great feature and I've used it to setup 1 click setup for non devs, but for people who want to contribue to html and css changes. You have to think about those who don't know what `/etc/hosts` is. I would think we would want to drive to near complete automation as possible. I tried to handoff the Laravel Homestead docs and it wasn't enough, if you want an entire team working on a project it has to just be `vagrant up` somehow.

Would you just clone homestead per docs and customize and everything? Problem is then you can't easily upgrade (points to Laravel 5).

It would be awesome if this was possible without changes to homestead.rb as in some kind of after hook (not after.sh), but like provisioned.rb or something which would let anyone add this functionality, or even homestead plugins where people could load up to extend it to whatever you guys don't care to merge.

**Comment by richdynamix** [comment]
Rather than relying on homestead to modify the host machine it would make more sense to use something like DNSmasq (http://www.thekelleys.org.uk/dnsmasq/doc.html) to automatically route your host to the guest. 

```
192.168.10.10 *.dev
```

This can be achieved by setting the configuration to something like

```
address=/dev/192.168.10.10
```

**Pull request closed without merging**
