### PR TITLE
Unique Hostname CN for Root Certificate

### PR DESCRIPTION
**Pull request by Artistan**
Allow for unique hostname configuration to differentiate between root certs.

### CODE REVIEW

**Comment by browner12** [comment]
is this because you have multiple Homestead installs on one machine?

**Comment by svpernova09** [comment]
The root certificates are what people are pulling out of the vagrant box and importing into their browsers?

if so we should make it 1000% absolutely clear it's a HOMESTEAD generated certificate. So I'm not against naming this the host name of the machine, but I'd want to also append `_HOMESTEAD`.

**Comment by browner12** [comment]
good idea.

**Comment by Artistan** [comment]
@browner12 
Yes, this is due to multiple boxes, plus it is more descriptive for looking at your certs.
I have also automated my cert addition and destruction with shell scripts via up and destroy processes using the unique naming conventions.

**Comment by svpernova09** [comment]
Thanks for the PR!

**Pull request merged**
