### PR TITLE
Revert "Remove code directory"

### PR DESCRIPTION
**Pull request by svpernova09**
Reverts laravel/homestead#672

### CODE REVIEW

**Comment by svpernova09** [comment]
Reverting this for now. it's currently overriding the default home folder of `/home/vagrant`

**Comment by DojoGeekRA** [comment]
😓 i'm so sorry for this, the failure makes sense.

@svpernova09 should we preserve then the `code` directory in this cases or do you have another approach in mind?

**Comment by svpernova09** [comment]
@DojoGeekRA 

No worries at all. I didn't catch it either, and it explains why there is a code directory to begin with. i think we may leave it as is for now. But make sure the per project (make command) doesn't use it. Since we don't know what a user may be doing on a global install we want that code folder to protect them from this kind of bug. With the make command, we know exactly the path they're using so the code folder is only adding another level to traverse and we can easily skip it.

**Comment by DojoGeekRA** [comment]
@svpernova09 understood, i agree with you and will work on that, thanks! 😃

**Pull request merged**
