### PR TITLE
MariaDB updated to version 10.4

### PR DESCRIPTION
**Pull request by afgloeden**
I changed the script to use version `10.4` of the MariaDB repository.

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks for the PR.

Any idea if we can drop the version and get the latest version via `apt-get install mariadb-server`?

**Comment by afgloeden** [comment]
I will work on that.

**Comment by afgloeden** [comment]
Fixed.

**Comment by svpernova09** [comment]
Did it install 10.4 as we expected?

**Comment by afgloeden** [comment]
Yes.

```shell
vagrant@homestead:~$ mysql --version
mysql  Ver 15.1 Distrib 10.4.4-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by svpernova09** [comment]
Thanks for the quick turnaround!

**Comment by afgloeden** [comment]
No problem.

**Pull request merged**
