### PR TITLE
explicitly set nfs version on synced folders

### PR DESCRIPTION
**Pull request by pedrofornaza**
I had the error "mount.nfs: access denied by server while mounting" when mounting whitout this.

### CODE REVIEW

**Comment by taylorotwell** [comment]
@joshfng does this right to you?

**Comment by pedrofornaza** [comment]
If its not a common problem, we can put on Homestead.yaml.

**Comment by joshfng** [comment]
@taylorotwell I've never experienced any issues with the standard nfs setup, but I'm not an expert on the subject.

**Comment by taylorotwell** [comment]
Closing this for lack of other reported issues here.

**Comment by pawlobanano** [comment]
@pedrofornaza In my case adding ",vers=3" just after "actimeo=1" helps too.
Without it NFS couldn't mount shared folders.
Tested on linux Fedora 22.

**Comment by pedrofornaza** [comment]
@pawlobanano Thanks for reporting. We can now set the mount options on Homestead.yml using: mount_opts: ['actimeo=1,vers=3']

**Pull request closed without merging**
