### PR TITLE
Implement WSL-specific commands and documentation updates for wsl installation

### PR DESCRIPTION
**Pull request by karmendra**
- Added a new PHP script, `WslApplyFolderMapping.php`, to handle folder mapping in WSL from Homestead configuration.
- Created a new command `wsl:folders` to configure folder mapping in WSL.
- Renamed the command from `wsl:create-databases` to `wsl:databases` for consistency.
- Renamed the command from `wsl:create-sites` to `wsl:sites` for consistency.
- Updated the commands to print shell output using `print_r` instead of `var_dump`.
- Updated the PHP script `WslCreateSiteCommand.php` to configure sites in Nginx for WSL.
- Updated the PHP script, `WslCreateDatabaseCommand.php`, to create databases in WSL from Homestead configuration.
- Added documentation for setting up Homestead on WSL in wsl.md, including installation, optional features, database creation, configuring Nginx sites, and configuring shared folders.
- Updated the PHP script `WslCreateSiteCommand.php` to configure laravel sites' cron schedule for WSL.

### CODE REVIEW

**Comment by svpernova09** [comment]
Looks like a [couple](https://github.com/laravel/homestead/pull/1956/commits/16bd97671dd060c536db57630334874fc1d42a03) of changesin `bin/wsl-init` other than the rename to `bin/wsl-init.sh` (which I don't think we need. Line 1 of the script contains the info).

Can you back out your changes to `bin/wsl-init` and keep the rest of the changes? I want to get this and #1949 together in the same branch.

**Comment by svpernova09** [comment]
Let's target branch `wsl-rework` with this PR as the feature branch for this work.

**Comment by karmendra** [comment]
> Looks like a [couple](https://github.com/laravel/homestead/pull/1956/commits/16bd97671dd060c536db57630334874fc1d42a03) of changesin `bin/wsl-init` other than the rename to `bin/wsl-init.sh` (which I don't think we need. Line 1 of the script contains the info).

I delete wsl-init.sh, for now. If you need any change from `wsl-init.sh` moved in `wsl-init` let me know. I had added 
1. Changing current working directory to Homestead directory
2. Configured logging
3. Lot of validations (sudo, Ubuntu version, WSL_USER_NAME and WSL_USER_GROUP validations)
4. I had defaulted the script to install mysql instead of mariadb.

> Can you back out your changes to `bin/wsl-init` and keep the rest of the changes? I want to get this and #1949 together in the same branch.

I didn't modify wsl-init in this PR.

**Comment by karmendra** [comment]
There are [conflicts](https://github.com/laravel/homestead/pull/1956/conflicts) in 
`scripts/features/postgresql.sh` and `src/WslCreateSiteCommand.php`

Shall I remove my changes or you will be able to fix those?

**Comment by karmendra** [comment]
> Shall I remove my changes or you will be able to fix those?

I removed my changes and fixed the issue.

Please mind that I come from bitbucket background, so pardon my ignorance with github, if any, guide me if required. Thanks.

**Comment by MichaelBelgium** [comment]
There's still something wrong with the merge i think, it like completely failed or something

For instance

* svpernova09 already created a postgresql feature script in the branch wsl-rework, but how come git wants to add one from this branch or replace.

https://github.com/laravel/homestead/blob/wsl-rework/scripts/features/postgresql.sh

* The wsl-init in your branch isn't updated to the one from wsl-rework

**Comment by karmendra** [comment]
There is something not straight forward, allow me today, I will fix it.

**Comment by karmendra** [comment]
I tried various git commands to fix this, but didn't work.

So I created a [fresh PR](https://github.com/laravel/homestead/pull/1958) to wsl-work branch itself. 

We can discard this PR and use the new one.

**Comment by svpernova09** [comment]
Thanks for the work here.

**Pull request closed without merging**
