### PR TITLE
Fix owner of /home/vagrant/.webdriverutils

### PR DESCRIPTION
**Pull request by ricardoseriani**
Closes #1109 

Signed-off-by: Ricardo Seriani <ricardo.seriani@gmail.com>

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks!

**Comment by browner12** [comment]
Sorry to jump on this PR. I seem to running into the same issue with `/home/vagrant/.npm`, and ends up with me running npm with `sudo`.  Is the fix the same thing?

**Comment by ricardoseriani** [comment]
> Sorry to jump on this PR. I seem to running into the same issue with `/home/vagrant/.npm`, and ends up with me running npm with `sudo`. Is the fix the same thing?

I'm no maintainer, but I think that you should copy the commands that you are using and log/error, then open an issue about this, so anyone could verify it for you.

**Comment by deviantintegral** [comment]
Since the box doesn't do significant provisioning after the first boot, running `sudo chown -Rv vagrant:vagrant ~/.npm` should fix things and save you from having to `sudo npm` until this is fixed.

**Comment by svpernova09** [comment]
Sounds like maybe we should add a specific inline `chown -R vagrant:vagrant /home/vagrant`?

**Comment by deviantintegral** [comment]
I was thinking the same thing. Another option would be to add a check with something like `find /home/vagrant -not -user vagrant -and -not -group vagrant` that errors out during builds if any results are found. That would alert us to new problems without blindly chown'ing the directory.

**Comment by svpernova09** [comment]
> I was thinking the same thing. Another option would be to add a check with something like find /home/vagrant -not -user vagrant -and -not -group vagrant that errors out during builds if any results are found. That would alert us to new problems without blindly chown'ing the directory.

fwiw Settler does a blind chown -R on the home folder as one of the last things during cleanup lol. Not opposed to having Homestead do it.

**Comment by ricardoseriani** [comment]
> Sounds like maybe we should add a specific inline `chown -R vagrant:vagrant /home/vagrant` that runs every time the box is provisioned?
> 
> btw tons of thanks to @ricardoseriani for cleaning up the messes I left <3

Wow, thanks a lot for the compliment 😊.
About the `chown -R vagrant:vagrant /home/vagrant`, anyone know what he does with the mapped folders ?
I'll try to discover this, because I'm afraid that it messes up with these folders.

**Comment by ricardoseriani** [comment]
Apparently, the 'chown -R vagrant:vagrant /home/vagrant` should not cause any problem, as it is stated in [https://github.com/hashicorp/vagrant/issues/897](https://github.com/hashicorp/vagrant/issues/897), on first and second comments.

I can make a PR with this, but I'm not certain what is the best way to ensure that this script will be the last running.

**Comment by svpernova09** [comment]
The more I think about it, Homestead doing a blind chown sounds gross. The only newly discovered issues here should be the features I "shifted", if we've fixed the chown on those installers, I'm happy to leave it at that.

**Comment by ricardoseriani** [comment]
For sure, I think it's best to doing this selectively than doing it in general /home/vagrant folder.

**Pull request merged**
