### PR TITLE
vmware_fusion provider support.

### PR DESCRIPTION
**Pull request by joshfng**
This depends on https://github.com/laravel/settler/pull/13 and would require that the laravel/homestead Vagrant image for both virtualbox and vmware_desktop exist before merging this.

### CODE REVIEW

**Comment by jfmercer** [comment]
+1

**Comment by mledu** [comment]
+1

**Comment by taylorotwell** [comment]
No plans to add support for this.

**Comment by mrlucmorin** [comment]
Disappointing.

**Comment by jfmercer** [comment]
Taylor,

If someone submitted a pull request that adds full support for VMware
Fusion, would you then consider merging it?

--jm

**Comment by JeffreyVdb** [comment]
Taylor, I respect your decision to not support it. But what is the reasoning? There are tools like packer that enable you to maintain multiple providers, keeping software that's installed perfectly in sync simply by adding to a script.

Would you be willing to give more insight on how you crafted homestead, did you do it manually, did you use packer? Would you be willing to use this if requested by someone?

**Comment by Youbility** [comment]
Too bad you don't want to add support for this. Is there any chance we could change your mind?

**Comment by svpernova09** [comment]
@JeffreyVdb You can see how the Homestead base box was built by looking at the [laravel/settler](github.com/laravel/settler) project

**Comment by mrlucmorin** [comment]
@svpernova09 I have tried to create my own from this, but I gave up for lack of time. Trying to grasp all those different concepts/tools is unfortunately out of my reach at the moment. That's why I wanted to see this come true.

**Pull request closed without merging**
