### PR TITLE
Updated homestead.rb to run commands directly.

### PR DESCRIPTION
**Pull request by Utkarsh-vishnoi**
Updated homestead.rb to run shell commands directly form homestead.yaml file.

### CODE REVIEW

**Comment by andrewhood125** [comment]
So `after.sh` gets run only on `vagrant provision` or initial `vagrant up` and this would get run after`vagrant up` only? I'd rather rename `after.sh => provision.sh` and then add a `up.sh`.

**Comment by svpernova09** [comment]
What is the use case for running shell commands from the `homestead.yaml` that seems very odd. If you need to run shell scripts add them to `after.sh`, if you need them to run _every_ time you boot vagrant than they should be added to the base box instead of Homestead. (this may mean creating your own box it's a one off thing that doesn't fit Homestead)

**Comment by Utkarsh-vishnoi** [comment]
How exactly I am gonna run a command for each and every-time I do `vagrant up`. I wanna do this Because setting up homestead is easy then entirely configuring another base box.
If you got any other method that is not odd. I would love to hear it. :+1:

**Comment by svpernova09** [comment]
@Utkarsh-vishnoi If you are running a shell script every time you do `vagrant up` I'm saying that's not common in the typical vagrant workflow. The better option (Better than changing how Homestead works for everyone) would be to use `after.sh` to add a cron job to run on every boot (You'd want `@reboot` I believe for this) that runs your script from your project folder.

**Comment by Utkarsh-vishnoi** [comment]
OK

**Pull request closed without merging**
