### PR TITLE
Homestead v15 - Ubuntu 22.04 - PHP 8.3

### PR DESCRIPTION
**Pull request by svpernova09**
Ubuntu 22.04
PHP 8.3 Default
Add Golang to base box
Remove Drush Launcher
Remove Drupal Launcher
Replace MailHog with Mailpit

### CODE REVIEW

**Comment by browner12** [comment]
Congrats Joe! Thanks as always for all the hard work you put into this awesome project!

**Comment by browner12** [comment]
Surprised you built the Virtualbox version first, considering all the problems you seemed to have with it. Were there issues with the Parallels version, too, or is that guy on the way?

**Comment by svpernova09** [comment]
> Surprised you built the Virtualbox version first, considering all the problems you seemed to have with it. Were there issues with the Parallels version, too, or is that guy on the way?

I wanted to get the Virtualbox built and out as a test to see if I missed anything big. It's been a few days and so far so good. I'll get Parallels built and uploaded soon(tm)

**Comment by browner12** [comment]
Gotcha, thanks for the response!

**Comment by svpernova09** [comment]
> Gotcha, thanks for the response!

Parallels box uploaded.

**Comment by browner12** [comment]
So the recommendation previously was to be on the "release" branch when working in Homestead, which I see hasn't been updated with these changes. Are we changing how we do branching, or are you still considering this "pre-release"?

**Comment by svpernova09** [comment]
> So the recommendation previously was to be on the "release" branch when working in Homestead, which I see hasn't been updated with these changes. Are we changing how we do branching, or are you still considering this "pre-release"?

The box is ready for use, but you'd need to be on Homestead's `main` branch currently because I still haven't tagged a release. I've done my minimal testing but I'd love to hear another success before tagging. If you'd rather wait and not test drive that's fine too :D

**Comment by browner12** [comment]
Thanks for the clarification. I'll test out the Parallels ARM version on my home MacBook tonight.

**Comment by browner12** [comment]
I successfully got the new box running on my MacBook Pro tonight, with the ARM64 Parallels version. It even feels snappier than the old box!

Had some minimal issues, which I'll try to spell out here.

- in my `Homestead.yaml` file, I had a custom override `box` key pointing to the `laravel/homestead-arm` box. Probably a remnant from the very old days when the ARM version was first being built, but I needed to remove that for it to work.

I'd say to avoid confusion it would be nice if we could remove the `laravel/homestead-arm` box at https://app.vagrantup.com/laravel, but I'm not sure if that's allowed. Ideally we'd remove the other random boxes ("mariadb" and "7") as well.

There is also the warning of the use of the deprecated `apt-key`, which I believe we also had in the old box. It would be nice if we could make these updates to remove those warnings, and I'd definitely be willing to help with that.

Otherwise, the box seems to behaving just like before.

---

There do appear to be some issues that carried over from the previous version, probably unrelated to the box, and more related to the provision scripts.

- the "mysql" key is not a valid feature, and results in `Invalid feature: mysql`.  This might just be an example file and documentation we need to change.
- I am getting errors when setting the "web-driver" feature to `true`. It could possibly be related to the `apt-key` issues. Keeping this disabled allows the provision to continue.

I'll be on the LaraSlack tomorrow if you'd like to discuss any of these things in a more realtime setting.

Thanks!

**Comment by browner12** [comment]
One possible issue found. On a site that I have both the `cache_driver` and `session_driver` set to "redis", I'm getting a "Class "Redis" not found" error.  Trying to dig in why that might be happening, and will report back.  I always get confused by the PHP Redis Extension vs Predis stuff, so I'll have to re-familiarize myself with it.

**Comment by svpernova09** [comment]
> the "mysql" key is not a valid feature, and results in Invalid feature: mysql. This might just be an example file and documentation we need to change.

From my `Homestead.yaml`

```folders:
    - map: /Users/halo/Code/fresh
      to: /home/vagrant/fresh

sites:
    - map: fresh.test
      to: /home/vagrant/fresh/public

databases:
    - fresh

features:
    - mysql: true
    - ohmyzsh: false
    - webdriver: false

services:
    - mysql: true
```

`vagrant up` log:

```
vagrant up                                                                                                                                                 ─(09:13:41)(01/17/24)─┘
Bringing machine 'homestead' up with 'parallels' provider...
==> homestead: Registering VM image from the base box 'laravel/homestead'...
==> homestead: Creating new virtual machine as a linked clone of the box image...
==> homestead: Unregistering the box VM image...
==> homestead: Setting the default configuration for VM...
==> homestead: Checking if box 'laravel/homestead' version '14.0.0' is up to date...
==> homestead: Setting the name of the VM: homestead
==> homestead: Preparing network interfaces based on configuration...
    homestead: Adapter 0: shared
    homestead: Adapter 1: hostonly
==> homestead: Clearing any previously set network interfaces...
==> homestead: Forwarding ports...
    homestead: 80 => 8000
    homestead: 443 => 44300
==> homestead: Running 'pre-boot' VM customizations...
==> homestead: Booting VM...
==> homestead: Waiting for machine to boot. This may take a few minutes...
    homestead: SSH address: 10.211.55.114:22
    homestead: SSH username: vagrant
    homestead: SSH auth method: private key
    homestead: 
    homestead: Vagrant insecure key detected. Vagrant will automatically replace
    homestead: this with a newly generated keypair for better security.
    homestead: 
    homestead: Inserting generated public key within guest...
    homestead: Removing insecure key from the guest if it's present...
    homestead: Key inserted! Disconnecting and reconnecting using new SSH key...
==> homestead: Machine booted and ready!
==> homestead: Checking for Parallels Tools installed on the VM...
==> homestead: Setting hostname...
==> homestead: Configuring and enabling network interfaces...
==> homestead: Mounting shared folders...
    homestead: /vagrant => /Users/halo/Code/homestead
    homestead: /home/vagrant/fresh => /Users/halo/Code/fresh
==> homestead: Detected mount owner ID within mount options. (uid: 1000 guestpath: /home/vagrant/fresh)
==> homestead: Detected mount group ID within mount options. (gid: 1000 guestpath: /home/vagrant/fresh)
==> homestead: Running provisioner: file...
    homestead: /Users/halo/Code/homestead/aliases => /tmp/bash_aliases
==> homestead: Running provisioner: handle_aliases (shell)...
    homestead: Running: inline script
==> homestead: Running provisioner: setting authorize key (shell)...
    homestead: Running: inline script
    homestead: 
    homestead: ssh-rsa
    homestead: 
==> homestead: Running provisioner: setting authorize permissions for id_rsa (shell)...
    homestead: Running: inline script
==> homestead: Running provisioner: mk_features (shell)...
    homestead: Running: inline script
==> homestead: Running provisioner: own_features (shell)...
    homestead: Running: inline script
==> homestead: Running provisioner: apt_update (shell)...
    homestead: Running: inline script
    homestead: Get:1 https://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease [123 kB]
    homestead: Hit:2 https://deb.nodesource.com/node_21.x nodistro InRelease
    homestead: Get:3 https://download.docker.com/linux/ubuntu jammy InRelease [48.8 kB]
    homestead: Hit:4 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
    homestead: Get:5 https://apt.postgresql.org/pub/repos/apt jammy-pgdg/main arm64 Packages [293 kB]
    homestead: Get:6 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [119 kB]
    homestead: Hit:7 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy InRelease
    homestead: Hit:8 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease
    homestead: Get:9 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]
    homestead: Get:10 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 Packages [1,116 kB]
    homestead: Get:11 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main Translation-en [262 kB]
    homestead: Get:12 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted arm64 Packages [860 kB]
    homestead: Get:13 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted Translation-en [208 kB]
    homestead: Get:14 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages [957 kB]
    homestead: Get:15 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe Translation-en [228 kB]
    homestead: Get:16 http://ports.ubuntu.com/ubuntu-ports jammy-updates/multiverse arm64 Packages [24.0 kB]
    homestead: Get:17 http://ports.ubuntu.com/ubuntu-ports jammy-security/main arm64 Packages [908 kB]
    homestead: Get:18 http://ports.ubuntu.com/ubuntu-ports jammy-security/main Translation-en [201 kB]
    homestead: Get:19 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted arm64 Packages [851 kB]
    homestead: Get:20 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted Translation-en [204 kB]
    homestead: Get:21 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe arm64 Packages [764 kB]
    homestead: Get:22 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe Translation-en [158 kB]
    homestead: Fetched 7,435 kB in 3s (2,138 kB/s)
    homestead: Reading package lists...
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Invalid feature: mysql
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Ignoring feature: ohmyzsh because it is set to false
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Ignoring feature: webdriver because it is set to false
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/73/hkr4pszx5jj1_j6hffydbgsm0000gn/T/vagrant-shell20240117-10050-7w2vsz.sh
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/73/hkr4pszx5jj1_j6hffydbgsm0000gn/T/vagrant-shell20240117-10050-nq16l2.sh
==> homestead: Running provisioner: Creating Certificate: fresh.test (shell)...
    homestead: Running: script: Creating Certificate: fresh.test
    homestead: Updating certificates in /etc/ssl/certs...
    homestead: rehash: warning: skipping duplicate certificate in ca.homestead.homestead.pem
    homestead: rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
    homestead: 1 added, 0 removed; done.
    homestead: Running hooks in /etc/ca-certificates/update.d...
    homestead: done.
==> homestead: Running provisioner: Creating Site: fresh.test (shell)...
    homestead: Running: script: Creating Site: fresh.test
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/73/hkr4pszx5jj1_j6hffydbgsm0000gn/T/vagrant-shell20240117-10050-62rm7n.sh
==> homestead: Running provisioner: Checking for old Schedule (shell)...
    homestead: Running: script: Checking for old Schedule
==> homestead: Running provisioner: Clear Variables (shell)...
    homestead: Running: script: Clear Variables
==> homestead: Running provisioner: Restarting Cron (shell)...
    homestead: Running: script: Restarting Cron
==> homestead: Running provisioner: Restart Webserver (shell)...
    homestead: Running: script: Restart Webserver
==> homestead: Running provisioner: Creating MySQL / MariaDB Database: fresh (shell)...
    homestead: Running: script: Creating MySQL / MariaDB Database: fresh
==> homestead: Running provisioner: Update Composer (shell)...
    homestead: Running: script: Update Composer
    homestead: You are already using the latest available Composer version 2.6.6 (stable channel).
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/73/hkr4pszx5jj1_j6hffydbgsm0000gn/T/vagrant-shell20240117-10050-ww6cxn.sh
==> homestead: Running provisioner: Update motd (shell)...
    homestead: Running: script: Update motd
==> homestead: Running provisioner: Run after.sh (shell)...
    homestead: Running: /var/folders/73/hkr4pszx5jj1_j6hffydbgsm0000gn/T/vagrant-shell20240117-10050-7bd2g5.sh
vagrant up: 01:18
```

Once in the VM I can see the `fresh` DB created as expected.

```
vagrant@homestead:~$ mysql -e 'show databases;'
+--------------------+
| Database           |
+--------------------+
| fresh              |
| homestead          |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
vagrant@homestead:~$ 
```

Might be a docs need updating issue. But this is the currently intended way.

**Comment by svpernova09** [comment]
> I am getting errors when setting the "web-driver" feature to true. It could possibly be related to the apt-key issues. Keeping this disabled allows the provision to continue.

Confirmed the webdriver feature is broken. Needs to be updated to something ~

```
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmour -o /usr/share/keyrings/chrome-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list'
```

But we need a condition check for arch in the `echo`.

**Comment by browner12** [comment]
Here is my `php -m` output for an old build vs a new build.

OLD

```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
imap
intl
json
ldap
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
random
readline
redis
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

NEW

```

```

**Pull request merged**
