### PR TITLE
Fix issues with $_ENV on Windows

### PR DESCRIPTION
**Pull request by maddhatter**
This fixes issues with 2.0.8 on Windows (being discussed on 167135b).

I've tested this on Windows 8.1 (6.3.9600) and the Windows 10 technical preview (6.4.9879). I don't have any older versions of Windows handy, but it should work on those as well.

### CODE REVIEW

**Comment by Fed03** [comment]
up @taylorotwell :sunglasses:

**Comment by enrichit** [comment]
If you're desperate to get it running just copy the files in this repo over to `%APPDATA%\Roaming\Composer\vendor\laravel\homestead`.

**Comment by radum** [comment]
I'm on Win7 x64 and this works perfectly. So ping @taylorotwell :grinning:

**Comment by matteoantoci** [comment]
+1

**Comment by martinssipenko** [comment]
+1

**Pull request merged**
