### PR TITLE
Reverse Proxy Script/Alias

### PR DESCRIPTION
**Pull request by CodyBohn**
Added a script and relevant alias to make provisioning a reverse proxy using nginx fast/simple.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What do you use this for on Homestead?

**Comment by CodyBohn** [comment]
I manually wrote configs for self-serving software (e.g. node) like redis-commander. The process was very similar to the existing serve scripts so I just adapted it.

**Comment by taylorotwell** [comment]
So if you set one up for redis-commander what does that then allow you to do? Sorry just trying to understand the use case.

**Comment by CodyBohn** [comment]
I completely understand. It might be uncommon but it's convenient for me so I thought I would share.

In essence it allows you to treat services that expose themselves directly on a port (e.g. 8080) as another project accessible at http://redis.app rather than 192.168.10.10:8080 or homestead.app:8080.

I reference it in my after.sh for serving redis-commander. I also use it for front end projects that serve themselves and do hot reloading during development. The proxy portion is native to nginx.

I hope that does a better job of explaining it.

**Pull request merged**
