### PR TITLE
Add new site type for webman framework

### PR DESCRIPTION
**Pull request by svpernova09**
/cc @mouyong

Resolves https://github.com/laravel/homestead/issues/1764

Example configuration:

```
sites:
    - map: vcdt.test
      to: /home/vagrant/vcdt/public
      type: webman
      webman_port: 9393
```

Results in the following virutalhost:

```
upstream webman {
    server 127.0.0.1:9393;
}

server {
    listen 80;
    listen 443 ssl http2;
    server_name .vcdt.test;
    root "/home/vagrant/vcdt/public";

    index index.html index.htm index.php;

    charset utf-8;



    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;


        if (!-f $request_filename){
          proxy_pass http://webman;
        }
    }



    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/vcdt.test-error.log error;

    sendfile off;

    location ~ /\.ht {
        deny all;
    }

    ssl_certificate     /etc/ssl/certs/vcdt.test.crt;
    ssl_certificate_key /etc/ssl/certs/vcdt.test.key;
}
```

### CODE REVIEW

**Comment by mouyong** [comment]
maybe we can add new site type for hyperf, it also need use upstream_port:

you can see this link.

https://hyperf.wiki/2.2/#/zh-cn/tutorial/nginx

image

image

**Comment by svpernova09** [comment]
> maybe we can add new site type for hyperf, it also need use upstream_port:
> 
> you can see this link.
> 

If it's the same syntax as the `webman` you can use that same type.

**Comment by mouyong** [comment]
Possible upstream_prpt than webman_port is more suitable. Why not use it.

And we can also add the websocket_port to variable 12: site['websocket_port'] ||= $12, # $12

**Comment by mouyong** [comment]
if site need `websocket_port`, it can be use `$12`，
if site need use `upstream` to listen application, it can be use `$11`.

**Comment by mouyong** [comment]
and the `webman_port` just used by webman framework.

**Comment by mouyong** [comment]
And `webman_port` is a PHP framework setting, and the `upstream_port` and the `websocket_port` are nginx settings.

**Comment by svpernova09** [comment]
Apologies, I haven't forgotten about this.

**Comment by svpernova09** [comment]
Closing this as I completely neglected it. if you'd like to PR a webman site type I'll happily review it.

**Pull request closed without merging**
