### PR TITLE
Add the posibiltiy to use JSON as config file

### PR DESCRIPTION
**Pull request by leonhh**
I have had some problems when using YAML on a windows machine. The ruby YAML parser on windows is not functioning good for me and I like to write my config in JSON(which is even more familiar for most web developers). To use you can just use the make command with the --json flag and a json config file will be copied to the root directory of your project.

### CODE REVIEW

**Comment by w2pc** [comment]
I like this idea just because..

**Comment by taylorotwell** [comment]
Better to be opinionated on these things. Less overhead to maintain.

**Comment by leonhh** [comment]
@taylorotwell the reason of this PR is that the YAML parser on windows doesn't work as it does on OSX & linux. See also this http://laravel.io/forum/06-13-2014-ruby-errors-after-vagrant-up

I spend hours adjusting my homestead.yaml file before I started writing this and using the JSON parser it worked like a charm. It is more a bug than a something i am opinionated about.

**Comment by svpernova09** [comment]
Would it be possible to use a command to convert the YAML file to JSON and then have a flag that is used to tell homestead to read from YAML or JSON?

**Comment by w2pc** [comment]
Sometimes overhead is not always a bad thing. As noted there is sometimes
issues with yaml on windows. I don't  think anyone disputes that.

**Comment by andrewhood125** [comment]
Well I think what @svpernova09 is getting at is all Homestead has to do is accept and read from a JSON file. By converting YAML to JSON you don't have to maintain two stubs. It would be minimal overhead. We could even make it look for a Homestead.yaml file first and fallback to a JSON if that's not found and that would be a very minimal change.

**Comment by andrewhood125** [comment]
#230 is an example.

**Pull request closed without merging**
