### PR TITLE
Get latest settler

### PR DESCRIPTION
**Pull request by lloricode**
To allow download settler 10.0.0

### CODE REVIEW

**Comment by svpernova09** [comment]
If you want to use the latest settler, use Homestead branch 20.04.

**Comment by lloricode** [comment]
> If you want to use the latest settler, use Homestead branch 20.04.

Thanks, did not notice that

**Comment by lloricode** [comment]
@svpernova09 i think there something wrong in here
https://github.com/laravel/homestead/blob/c045198cc1f47bd6daf79e9fb2e4efcc26f52b39/readme.md

Screenshot from 2020-07-22 02-03-15

**Comment by lloricode** [comment]
can i fix PR to the branch? if there wrong?

**Comment by lloricode** [comment]
@svpernova09 already fix in master branch, thanks by the way

**Pull request closed without merging**
