### PR TITLE
Fix StyleCI issues

### PR DESCRIPTION
**Pull request by driesvints**
This should fix the failing StyleCI build.

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks for the PR.


Is StyleCI supposed to auto fix this stuff for us? I wasn't sure so I merged the changes anyway, apparently it didn't. RE: https://github.com/laravel/homestead/pull/445#issuecomment-278384793

**Comment by GrahamCampbell** [comment]
Auto Fixing probably just isn't turned on for this repo. It's off by default. I can turn it on if we want.

**Comment by GrahamCampbell** [comment]
Ok, turned on now.

**Comment by svpernova09** [comment]
Thanks Graham.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Pull request merged**
